apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zvzx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0007-tenant/tkrw-pr712-0075-0007-app/devfile-sample-zvzx@sha256:e8582f9e265b2fd3834e9f7a24467e285cf983b8ac881c6374d54ce2b765931c
        name: my-nodejs
        resources: {}
status: {}
